name: GitHub Pages
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'

      - name: Install mdbook-theme
        uses: baptiste0928/cargo-install@v3
        with:
          crate: mdbook-theme
          git: https://github.com/zjp-CN/mdbook-theme

      - name: Install mdbook-admonish
        uses: baptiste0928/cargo-install@v3
        with:
          crate: mdbook-admonish
          git: https://github.com/tommilligan/mdbook-admonish

      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
